version: "3"
services:
  web:
    restart: always
    image: nginx:1.17
    ports:
      - 80:80
    links:
      - issue-feedback-react:app
    depends_on:
      - issue-feedback-react
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  issue-feedback-react:
    restart: always
    image: node:12.16
    working_dir: /opt/app
    volumes:
      - ../app/:/opt/app
    command: npm start
    stdin_open: true
